// Generated by gencpp from file simu_msgs/VehicleLength.msg
// DO NOT EDIT!


#ifndef SIMU_MSGS_MESSAGE_VEHICLELENGTH_H
#define SIMU_MSGS_MESSAGE_VEHICLELENGTH_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace simu_msgs
{
template <class ContainerAllocator>
struct VehicleLength_
{
  typedef VehicleLength_<ContainerAllocator> Type;

  VehicleLength_()
    : value(0)
    , confidence_indication(0)  {
    }
  VehicleLength_(const ContainerAllocator& _alloc)
    : value(0)
    , confidence_indication(0)  {
  (void)_alloc;
    }



   typedef uint16_t _value_type;
  _value_type value;

   typedef uint8_t _confidence_indication_type;
  _confidence_indication_type confidence_indication;



  enum {
    VALUE_TEN_CENTIMETERS = 1u,
    VALUE_OUT_OF_RANGE = 1022u,
    VALUE_UNAVAILABLE = 1023u,
    CONFIDENCE_INDICATION_NO_TRAILER = 0u,
    CONFIDENCE_INDICATION_TRAILER_WITH_KNOWN_LENGTH = 1u,
    CONFIDENCE_INDICATION_TRAILER_WITH_UNKNOWN_LENGTH = 2u,
    CONFIDENCE_INDICATION_UNKNOWN_TRAILER_PRESENCE = 3u,
    CONFIDENCE_INDICATION_UNAVAILABLE = 4u,
  };


  typedef boost::shared_ptr< ::simu_msgs::VehicleLength_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::simu_msgs::VehicleLength_<ContainerAllocator> const> ConstPtr;

}; // struct VehicleLength_

typedef ::simu_msgs::VehicleLength_<std::allocator<void> > VehicleLength;

typedef boost::shared_ptr< ::simu_msgs::VehicleLength > VehicleLengthPtr;
typedef boost::shared_ptr< ::simu_msgs::VehicleLength const> VehicleLengthConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::simu_msgs::VehicleLength_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::simu_msgs::VehicleLength_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace simu_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'simu_msgs': ['/home/ppe2021/catkin_ws/src/simu_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::simu_msgs::VehicleLength_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simu_msgs::VehicleLength_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simu_msgs::VehicleLength_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simu_msgs::VehicleLength_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simu_msgs::VehicleLength_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simu_msgs::VehicleLength_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::simu_msgs::VehicleLength_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bf077d96b456d30e08df07f0d831fe92";
  }

  static const char* value(const ::simu_msgs::VehicleLength_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbf077d96b456d30eULL;
  static const uint64_t static_value2 = 0x08df07f0d831fe92ULL;
};

template<class ContainerAllocator>
struct DataType< ::simu_msgs::VehicleLength_<ContainerAllocator> >
{
  static const char* value()
  {
    return "simu_msgs/VehicleLength";
  }

  static const char* value(const ::simu_msgs::VehicleLength_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::simu_msgs::VehicleLength_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 value # 0.1 meter\n\
uint8 confidence_indication\n\
\n\
uint16 VALUE_TEN_CENTIMETERS = 1\n\
uint16 VALUE_OUT_OF_RANGE = 1022\n\
uint16 VALUE_UNAVAILABLE = 1023\n\
\n\
uint8 CONFIDENCE_INDICATION_NO_TRAILER = 0\n\
uint8 CONFIDENCE_INDICATION_TRAILER_WITH_KNOWN_LENGTH = 1\n\
uint8 CONFIDENCE_INDICATION_TRAILER_WITH_UNKNOWN_LENGTH = 2\n\
uint8 CONFIDENCE_INDICATION_UNKNOWN_TRAILER_PRESENCE = 3\n\
uint8 CONFIDENCE_INDICATION_UNAVAILABLE = 4\n\
";
  }

  static const char* value(const ::simu_msgs::VehicleLength_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::simu_msgs::VehicleLength_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value);
      stream.next(m.confidence_indication);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VehicleLength_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::simu_msgs::VehicleLength_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::simu_msgs::VehicleLength_<ContainerAllocator>& v)
  {
    s << indent << "value: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.value);
    s << indent << "confidence_indication: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.confidence_indication);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIMU_MSGS_MESSAGE_VEHICLELENGTH_H
