// Generated by gencpp from file ece_msgs/FreinageUrgence.msg
// DO NOT EDIT!


#ifndef ECE_MSGS_MESSAGE_FREINAGEURGENCE_H
#define ECE_MSGS_MESSAGE_FREINAGEURGENCE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ece_msgs
{
template <class ContainerAllocator>
struct FreinageUrgence_
{
  typedef FreinageUrgence_<ContainerAllocator> Type;

  FreinageUrgence_()
    : position(0)  {
    }
  FreinageUrgence_(const ContainerAllocator& _alloc)
    : position(0)  {
  (void)_alloc;
    }



   typedef uint8_t _position_type;
  _position_type position;





  typedef boost::shared_ptr< ::ece_msgs::FreinageUrgence_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ece_msgs::FreinageUrgence_<ContainerAllocator> const> ConstPtr;

}; // struct FreinageUrgence_

typedef ::ece_msgs::FreinageUrgence_<std::allocator<void> > FreinageUrgence;

typedef boost::shared_ptr< ::ece_msgs::FreinageUrgence > FreinageUrgencePtr;
typedef boost::shared_ptr< ::ece_msgs::FreinageUrgence const> FreinageUrgenceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ece_msgs::FreinageUrgence_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ece_msgs::FreinageUrgence_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ece_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'ece_msgs': ['/home/ppe2021/catkin_ws/src/ece_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ece_msgs::FreinageUrgence_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ece_msgs::FreinageUrgence_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ece_msgs::FreinageUrgence_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ece_msgs::FreinageUrgence_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ece_msgs::FreinageUrgence_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ece_msgs::FreinageUrgence_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ece_msgs::FreinageUrgence_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6dd1aa2cda989887d566114cab493168";
  }

  static const char* value(const ::ece_msgs::FreinageUrgence_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6dd1aa2cda989887ULL;
  static const uint64_t static_value2 = 0xd566114cab493168ULL;
};

template<class ContainerAllocator>
struct DataType< ::ece_msgs::FreinageUrgence_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ece_msgs/FreinageUrgence";
  }

  static const char* value(const ::ece_msgs::FreinageUrgence_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ece_msgs::FreinageUrgence_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Position P : 2 bits\n\
uint8 position\n\
";
  }

  static const char* value(const ::ece_msgs::FreinageUrgence_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ece_msgs::FreinageUrgence_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FreinageUrgence_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ece_msgs::FreinageUrgence_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ece_msgs::FreinageUrgence_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ECE_MSGS_MESSAGE_FREINAGEURGENCE_H
