// Generated by gencpp from file ece_msgs/IDs.msg
// DO NOT EDIT!


#ifndef ECE_MSGS_MESSAGE_IDS_H
#define ECE_MSGS_MESSAGE_IDS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ece_msgs
{
template <class ContainerAllocator>
struct IDs_
{
  typedef IDs_<ContainerAllocator> Type;

  IDs_()
    : ID(0)
    , position(0)  {
    }
  IDs_(const ContainerAllocator& _alloc)
    : ID(0)
    , position(0)  {
  (void)_alloc;
    }



   typedef uint8_t _ID_type;
  _ID_type ID;

   typedef uint8_t _position_type;
  _position_type position;





  typedef boost::shared_ptr< ::ece_msgs::IDs_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ece_msgs::IDs_<ContainerAllocator> const> ConstPtr;

}; // struct IDs_

typedef ::ece_msgs::IDs_<std::allocator<void> > IDs;

typedef boost::shared_ptr< ::ece_msgs::IDs > IDsPtr;
typedef boost::shared_ptr< ::ece_msgs::IDs const> IDsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ece_msgs::IDs_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ece_msgs::IDs_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ece_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'ece_msgs': ['/home/ppe2021/catkin_ws/src/ece_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ece_msgs::IDs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ece_msgs::IDs_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ece_msgs::IDs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ece_msgs::IDs_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ece_msgs::IDs_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ece_msgs::IDs_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ece_msgs::IDs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f033ee2c58d32e679065279d1059f93e";
  }

  static const char* value(const ::ece_msgs::IDs_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf033ee2c58d32e67ULL;
  static const uint64_t static_value2 = 0x9065279d1059f93eULL;
};

template<class ContainerAllocator>
struct DataType< ::ece_msgs::IDs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ece_msgs/IDs";
  }

  static const char* value(const ::ece_msgs::IDs_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ece_msgs::IDs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 ID\n\
uint8 position\n\
";
  }

  static const char* value(const ::ece_msgs::IDs_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ece_msgs::IDs_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ID);
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IDs_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ece_msgs::IDs_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ece_msgs::IDs_<ContainerAllocator>& v)
  {
    s << indent << "ID: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ID);
    s << indent << "position: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ECE_MSGS_MESSAGE_IDS_H
