// Generated by gencpp from file ece_msgs/Init.msg
// DO NOT EDIT!


#ifndef ECE_MSGS_MESSAGE_INIT_H
#define ECE_MSGS_MESSAGE_INIT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <ece_msgs/ReferencePosition.h>
#include <ece_msgs/ReferencePosition.h>

namespace ece_msgs
{
template <class ContainerAllocator>
struct Init_
{
  typedef Init_<ContainerAllocator> Type;

  Init_()
    : destination()
    , actual_position()  {
    }
  Init_(const ContainerAllocator& _alloc)
    : destination(_alloc)
    , actual_position(_alloc)  {
  (void)_alloc;
    }



   typedef  ::ece_msgs::ReferencePosition_<ContainerAllocator>  _destination_type;
  _destination_type destination;

   typedef  ::ece_msgs::ReferencePosition_<ContainerAllocator>  _actual_position_type;
  _actual_position_type actual_position;





  typedef boost::shared_ptr< ::ece_msgs::Init_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ece_msgs::Init_<ContainerAllocator> const> ConstPtr;

}; // struct Init_

typedef ::ece_msgs::Init_<std::allocator<void> > Init;

typedef boost::shared_ptr< ::ece_msgs::Init > InitPtr;
typedef boost::shared_ptr< ::ece_msgs::Init const> InitConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ece_msgs::Init_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ece_msgs::Init_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ece_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'ece_msgs': ['/home/ppe2021/catkin_ws/src/ece_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ece_msgs::Init_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ece_msgs::Init_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ece_msgs::Init_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ece_msgs::Init_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ece_msgs::Init_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ece_msgs::Init_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ece_msgs::Init_<ContainerAllocator> >
{
  static const char* value()
  {
    return "98e72c61b91b7db811fccea348b6d240";
  }

  static const char* value(const ::ece_msgs::Init_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x98e72c61b91b7db8ULL;
  static const uint64_t static_value2 = 0x11fccea348b6d240ULL;
};

template<class ContainerAllocator>
struct DataType< ::ece_msgs::Init_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ece_msgs/Init";
  }

  static const char* value(const ::ece_msgs::Init_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ece_msgs::Init_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Destination : 8 octets\n\
ReferencePosition destination\n\
\n\
# Actual position : 8 octets\n\
ReferencePosition actual_position\n\
\n\
\n\
\n\
================================================================================\n\
MSG: ece_msgs/ReferencePosition\n\
int64 latitude # 0.1 micro degree\n\
int64 longitude # 0.1 micro degree\n\
int32 altitude\n\
\n\
int64 LATITUDE_UNAVAILABLE = 900000001\n\
int64 LONGITUDE_UNAVAILABLE = 1800000001\n\
int32 ALTITUDE_UNAVAILABLE = 800001\n\
";
  }

  static const char* value(const ::ece_msgs::Init_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ece_msgs::Init_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.destination);
      stream.next(m.actual_position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Init_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ece_msgs::Init_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ece_msgs::Init_<ContainerAllocator>& v)
  {
    s << indent << "destination: ";
    s << std::endl;
    Printer< ::ece_msgs::ReferencePosition_<ContainerAllocator> >::stream(s, indent + "  ", v.destination);
    s << indent << "actual_position: ";
    s << std::endl;
    Printer< ::ece_msgs::ReferencePosition_<ContainerAllocator> >::stream(s, indent + "  ", v.actual_position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ECE_MSGS_MESSAGE_INIT_H
