// Generated by gencpp from file ece_msgs/Phase.msg
// DO NOT EDIT!


#ifndef ECE_MSGS_MESSAGE_PHASE_H
#define ECE_MSGS_MESSAGE_PHASE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ece_msgs
{
template <class ContainerAllocator>
struct Phase_
{
  typedef Phase_<ContainerAllocator> Type;

  Phase_()
    : value(0)  {
    }
  Phase_(const ContainerAllocator& _alloc)
    : value(0)  {
  (void)_alloc;
    }



   typedef uint8_t _value_type;
  _value_type value;



  enum {
    INIT = 0u,
    INSERTION = 1u,
    DESINSERTION = 2u,
    FEU = 3u,
    FREINAGE_URG = 4u,
  };


  typedef boost::shared_ptr< ::ece_msgs::Phase_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ece_msgs::Phase_<ContainerAllocator> const> ConstPtr;

}; // struct Phase_

typedef ::ece_msgs::Phase_<std::allocator<void> > Phase;

typedef boost::shared_ptr< ::ece_msgs::Phase > PhasePtr;
typedef boost::shared_ptr< ::ece_msgs::Phase const> PhaseConstPtr;

// constants requiring out of line definition

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ece_msgs::Phase_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ece_msgs::Phase_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ece_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'ece_msgs': ['/home/ppe2021/catkin_ws/src/ece_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ece_msgs::Phase_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ece_msgs::Phase_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ece_msgs::Phase_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ece_msgs::Phase_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ece_msgs::Phase_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ece_msgs::Phase_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ece_msgs::Phase_<ContainerAllocator> >
{
  static const char* value()
  {
    return "250a84fbe16f4f28908dcca677c4b00e";
  }

  static const char* value(const ::ece_msgs::Phase_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x250a84fbe16f4f28ULL;
  static const uint64_t static_value2 = 0x908dcca677c4b00eULL;
};

template<class ContainerAllocator>
struct DataType< ::ece_msgs::Phase_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ece_msgs/Phase";
  }

  static const char* value(const ::ece_msgs::Phase_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ece_msgs::Phase_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Phase de plattoning\n\
uint8 value\n\
\n\
uint8 INIT = 0\n\
uint8 INSERTION = 1\n\
uint8 DESINSERTION = 2\n\
uint8 FEU = 3\n\
uint8 FREINAGE_URG = 4\n\
";
  }

  static const char* value(const ::ece_msgs::Phase_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ece_msgs::Phase_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Phase_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ece_msgs::Phase_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ece_msgs::Phase_<ContainerAllocator>& v)
  {
    s << indent << "value: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ECE_MSGS_MESSAGE_PHASE_H
