// Generated by gencpp from file ece_msgs/ReferencePosition.msg
// DO NOT EDIT!


#ifndef ECE_MSGS_MESSAGE_REFERENCEPOSITION_H
#define ECE_MSGS_MESSAGE_REFERENCEPOSITION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ece_msgs
{
template <class ContainerAllocator>
struct ReferencePosition_
{
  typedef ReferencePosition_<ContainerAllocator> Type;

  ReferencePosition_()
    : latitude(0)
    , longitude(0)
    , altitude(0)  {
    }
  ReferencePosition_(const ContainerAllocator& _alloc)
    : latitude(0)
    , longitude(0)
    , altitude(0)  {
  (void)_alloc;
    }



   typedef int64_t _latitude_type;
  _latitude_type latitude;

   typedef int64_t _longitude_type;
  _longitude_type longitude;

   typedef int32_t _altitude_type;
  _altitude_type altitude;



  enum {
    LATITUDE_UNAVAILABLE = 900000001,
    LONGITUDE_UNAVAILABLE = 1800000001,
    ALTITUDE_UNAVAILABLE = 800001,
  };


  typedef boost::shared_ptr< ::ece_msgs::ReferencePosition_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ece_msgs::ReferencePosition_<ContainerAllocator> const> ConstPtr;

}; // struct ReferencePosition_

typedef ::ece_msgs::ReferencePosition_<std::allocator<void> > ReferencePosition;

typedef boost::shared_ptr< ::ece_msgs::ReferencePosition > ReferencePositionPtr;
typedef boost::shared_ptr< ::ece_msgs::ReferencePosition const> ReferencePositionConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ece_msgs::ReferencePosition_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ece_msgs::ReferencePosition_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ece_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'ece_msgs': ['/home/ppe2021/catkin_ws/src/ece_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ece_msgs::ReferencePosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ece_msgs::ReferencePosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ece_msgs::ReferencePosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ece_msgs::ReferencePosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ece_msgs::ReferencePosition_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ece_msgs::ReferencePosition_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ece_msgs::ReferencePosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5708c6f048e72dcc331b2c7a9cb6ac7f";
  }

  static const char* value(const ::ece_msgs::ReferencePosition_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5708c6f048e72dccULL;
  static const uint64_t static_value2 = 0x331b2c7a9cb6ac7fULL;
};

template<class ContainerAllocator>
struct DataType< ::ece_msgs::ReferencePosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ece_msgs/ReferencePosition";
  }

  static const char* value(const ::ece_msgs::ReferencePosition_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ece_msgs::ReferencePosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 latitude # 0.1 micro degree\n\
int64 longitude # 0.1 micro degree\n\
int32 altitude\n\
\n\
int64 LATITUDE_UNAVAILABLE = 900000001\n\
int64 LONGITUDE_UNAVAILABLE = 1800000001\n\
int32 ALTITUDE_UNAVAILABLE = 800001\n\
";
  }

  static const char* value(const ::ece_msgs::ReferencePosition_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ece_msgs::ReferencePosition_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.latitude);
      stream.next(m.longitude);
      stream.next(m.altitude);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReferencePosition_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ece_msgs::ReferencePosition_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ece_msgs::ReferencePosition_<ContainerAllocator>& v)
  {
    s << indent << "latitude: ";
    Printer<int64_t>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<int64_t>::stream(s, indent + "  ", v.longitude);
    s << indent << "altitude: ";
    Printer<int32_t>::stream(s, indent + "  ", v.altitude);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ECE_MSGS_MESSAGE_REFERENCEPOSITION_H
