// Generated by gencpp from file ece_msgs/VitesseInterdistance.msg
// DO NOT EDIT!


#ifndef ECE_MSGS_MESSAGE_VITESSEINTERDISTANCE_H
#define ECE_MSGS_MESSAGE_VITESSEINTERDISTANCE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <ece_msgs/Speed.h>

namespace ece_msgs
{
template <class ContainerAllocator>
struct VitesseInterdistance_
{
  typedef VitesseInterdistance_<ContainerAllocator> Type;

  VitesseInterdistance_()
    : speed()
    , interdistance(0)  {
    }
  VitesseInterdistance_(const ContainerAllocator& _alloc)
    : speed(_alloc)
    , interdistance(0)  {
  (void)_alloc;
    }



   typedef  ::ece_msgs::Speed_<ContainerAllocator>  _speed_type;
  _speed_type speed;

   typedef uint8_t _interdistance_type;
  _interdistance_type interdistance;





  typedef boost::shared_ptr< ::ece_msgs::VitesseInterdistance_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ece_msgs::VitesseInterdistance_<ContainerAllocator> const> ConstPtr;

}; // struct VitesseInterdistance_

typedef ::ece_msgs::VitesseInterdistance_<std::allocator<void> > VitesseInterdistance;

typedef boost::shared_ptr< ::ece_msgs::VitesseInterdistance > VitesseInterdistancePtr;
typedef boost::shared_ptr< ::ece_msgs::VitesseInterdistance const> VitesseInterdistanceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ece_msgs::VitesseInterdistance_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ece_msgs::VitesseInterdistance_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ece_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'ece_msgs': ['/home/ppe2021/catkin_ws/src/ece_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ece_msgs::VitesseInterdistance_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ece_msgs::VitesseInterdistance_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ece_msgs::VitesseInterdistance_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ece_msgs::VitesseInterdistance_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ece_msgs::VitesseInterdistance_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ece_msgs::VitesseInterdistance_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ece_msgs::VitesseInterdistance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d850ec0c0095939e4604e424c6859708";
  }

  static const char* value(const ::ece_msgs::VitesseInterdistance_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd850ec0c0095939eULL;
  static const uint64_t static_value2 = 0x4604e424c6859708ULL;
};

template<class ContainerAllocator>
struct DataType< ::ece_msgs::VitesseInterdistance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ece_msgs/VitesseInterdistance";
  }

  static const char* value(const ::ece_msgs::VitesseInterdistance_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ece_msgs::VitesseInterdistance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Vitesse : 6 bits\n\
Speed speed\n\
\n\
# Interdistance : 2 bits\n\
uint8 interdistance\n\
================================================================================\n\
MSG: ece_msgs/Speed\n\
uint16 value # 0.01 m/s\n\
uint8 confidence # 0.01 m/s\n\
\n\
uint16 VALUE_STANDSTILL = 0\n\
uint16 VALUE_ONE_CENTIMETER_PER_SECOND = 1\n\
uint16 VALUE_UNAVAILABLE = 16383\n\
\n\
uint8 CONFIDENCE_OUT_OF_RANGE = 126\n\
uint8 CONFIDENCE_UNAVAILABLE = 127\n\
";
  }

  static const char* value(const ::ece_msgs::VitesseInterdistance_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ece_msgs::VitesseInterdistance_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.speed);
      stream.next(m.interdistance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VitesseInterdistance_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ece_msgs::VitesseInterdistance_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ece_msgs::VitesseInterdistance_<ContainerAllocator>& v)
  {
    s << indent << "speed: ";
    s << std::endl;
    Printer< ::ece_msgs::Speed_<ContainerAllocator> >::stream(s, indent + "  ", v.speed);
    s << indent << "interdistance: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.interdistance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ECE_MSGS_MESSAGE_VITESSEINTERDISTANCE_H
