// Generated by gencpp from file etsi_msgs/BasicVehicleContainerLowFrequency.msg
// DO NOT EDIT!


#ifndef ETSI_MSGS_MESSAGE_BASICVEHICLECONTAINERLOWFREQUENCY_H
#define ETSI_MSGS_MESSAGE_BASICVEHICLECONTAINERLOWFREQUENCY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <etsi_msgs/VehicleRole.h>
#include <etsi_msgs/ExteriorLights.h>
#include <etsi_msgs/PathHistory.h>

namespace etsi_msgs
{
template <class ContainerAllocator>
struct BasicVehicleContainerLowFrequency_
{
  typedef BasicVehicleContainerLowFrequency_<ContainerAllocator> Type;

  BasicVehicleContainerLowFrequency_()
    : vehicle_role()
    , exterior_lights()
    , path_history()  {
    }
  BasicVehicleContainerLowFrequency_(const ContainerAllocator& _alloc)
    : vehicle_role(_alloc)
    , exterior_lights(_alloc)
    , path_history(_alloc)  {
  (void)_alloc;
    }



   typedef  ::etsi_msgs::VehicleRole_<ContainerAllocator>  _vehicle_role_type;
  _vehicle_role_type vehicle_role;

   typedef  ::etsi_msgs::ExteriorLights_<ContainerAllocator>  _exterior_lights_type;
  _exterior_lights_type exterior_lights;

   typedef  ::etsi_msgs::PathHistory_<ContainerAllocator>  _path_history_type;
  _path_history_type path_history;





  typedef boost::shared_ptr< ::etsi_msgs::BasicVehicleContainerLowFrequency_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::etsi_msgs::BasicVehicleContainerLowFrequency_<ContainerAllocator> const> ConstPtr;

}; // struct BasicVehicleContainerLowFrequency_

typedef ::etsi_msgs::BasicVehicleContainerLowFrequency_<std::allocator<void> > BasicVehicleContainerLowFrequency;

typedef boost::shared_ptr< ::etsi_msgs::BasicVehicleContainerLowFrequency > BasicVehicleContainerLowFrequencyPtr;
typedef boost::shared_ptr< ::etsi_msgs::BasicVehicleContainerLowFrequency const> BasicVehicleContainerLowFrequencyConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::etsi_msgs::BasicVehicleContainerLowFrequency_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::etsi_msgs::BasicVehicleContainerLowFrequency_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace etsi_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'etsi_msgs': ['/home/ppe2021/catkin_ws/src/etsi_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::etsi_msgs::BasicVehicleContainerLowFrequency_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::etsi_msgs::BasicVehicleContainerLowFrequency_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::etsi_msgs::BasicVehicleContainerLowFrequency_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::etsi_msgs::BasicVehicleContainerLowFrequency_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::etsi_msgs::BasicVehicleContainerLowFrequency_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::etsi_msgs::BasicVehicleContainerLowFrequency_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::etsi_msgs::BasicVehicleContainerLowFrequency_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5482aab88df6146441146840b8322331";
  }

  static const char* value(const ::etsi_msgs::BasicVehicleContainerLowFrequency_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5482aab88df61464ULL;
  static const uint64_t static_value2 = 0x41146840b8322331ULL;
};

template<class ContainerAllocator>
struct DataType< ::etsi_msgs::BasicVehicleContainerLowFrequency_<ContainerAllocator> >
{
  static const char* value()
  {
    return "etsi_msgs/BasicVehicleContainerLowFrequency";
  }

  static const char* value(const ::etsi_msgs::BasicVehicleContainerLowFrequency_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::etsi_msgs::BasicVehicleContainerLowFrequency_<ContainerAllocator> >
{
  static const char* value()
  {
    return "VehicleRole vehicle_role\n\
ExteriorLights exterior_lights\n\
PathHistory path_history\n\
\n\
================================================================================\n\
MSG: etsi_msgs/VehicleRole\n\
uint8 value\n\
\n\
uint8 DEFAULT = 0\n\
uint8 PUBLIC_TRANSPORT = 1\n\
uint8 SPECIAL_TRANSPORT = 2\n\
uint8 DANGEROUS_GOODS = 3\n\
uint8 ROAD_WORK = 4\n\
uint8 RESCUE = 5\n\
uint8 EMERGENCY = 6\n\
uint8 SAFETY_CAR = 7\n\
uint8 AGRICULTURE = 8\n\
uint8 COMMERCIAL = 9\n\
uint8 MILITARY = 10\n\
uint8 ROAD_OPERATOR = 11\n\
uint8 TAXI = 12\n\
\n\
================================================================================\n\
MSG: etsi_msgs/ExteriorLights\n\
uint8 value\n\
\n\
uint8 LOW_BEAM_HEADLIGHTS = 1\n\
uint8 HIGH_BEAM_HEADLIGHTS = 2\n\
uint8 LEFT_TURN_SIGNAL = 4\n\
uint8 RIGHT_TURN_SIGNAL = 8\n\
uint8 DAYTIME_RUNNING_LIGHTS = 16\n\
uint8 REVERSE_LIGHT = 32\n\
uint8 FOG_LIGHT = 64\n\
uint8 PARKING_LIGHTS = 128\n\
\n\
================================================================================\n\
MSG: etsi_msgs/PathHistory\n\
PathPoint[] points\n\
\n\
================================================================================\n\
MSG: etsi_msgs/PathPoint\n\
DeltaReferencePosition path_position\n\
PathDeltaTime path_delta_time\n\
\n\
================================================================================\n\
MSG: etsi_msgs/DeltaReferencePosition\n\
int32 delta_latitude # 0.1 micro degree\n\
int32 delta_longitude # 0.1 micro degree\n\
int16 delta_altitude # centimeter\n\
\n\
int32 ONE_MICRODEGREE_NORTH = 10\n\
int32 ONE_MICRODEGREE_SOUTH = -10\n\
int32 ONE_MICRODEGREE_EAST = 10\n\
int32 ONE_MICRODEGREE_WEST = -10\n\
int32 ONE_CENTIMETER_UP = 1\n\
int32 ONE_CENTIMETER_DOWN = -1\n\
int32 LATITUDE_UNAVAILABLE = 131072\n\
int32 LONGITUDE_UNAVAILABLE = 131072\n\
int16 ALTITUDE_UNAVAILABLE = 12800\n\
\n\
================================================================================\n\
MSG: etsi_msgs/PathDeltaTime\n\
uint16 value # 10 ms\n\
\n\
uint16 UNAVAILABLE = 0\n\
uint16 TEN_MILLISECONDS_IN_PAST = 1\n\
";
  }

  static const char* value(const ::etsi_msgs::BasicVehicleContainerLowFrequency_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::etsi_msgs::BasicVehicleContainerLowFrequency_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vehicle_role);
      stream.next(m.exterior_lights);
      stream.next(m.path_history);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BasicVehicleContainerLowFrequency_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::etsi_msgs::BasicVehicleContainerLowFrequency_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::etsi_msgs::BasicVehicleContainerLowFrequency_<ContainerAllocator>& v)
  {
    s << indent << "vehicle_role: ";
    s << std::endl;
    Printer< ::etsi_msgs::VehicleRole_<ContainerAllocator> >::stream(s, indent + "  ", v.vehicle_role);
    s << indent << "exterior_lights: ";
    s << std::endl;
    Printer< ::etsi_msgs::ExteriorLights_<ContainerAllocator> >::stream(s, indent + "  ", v.exterior_lights);
    s << indent << "path_history: ";
    s << std::endl;
    Printer< ::etsi_msgs::PathHistory_<ContainerAllocator> >::stream(s, indent + "  ", v.path_history);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ETSI_MSGS_MESSAGE_BASICVEHICLECONTAINERLOWFREQUENCY_H
