// Generated by gencpp from file etsi_msgs/ExteriorLights.msg
// DO NOT EDIT!


#ifndef ETSI_MSGS_MESSAGE_EXTERIORLIGHTS_H
#define ETSI_MSGS_MESSAGE_EXTERIORLIGHTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace etsi_msgs
{
template <class ContainerAllocator>
struct ExteriorLights_
{
  typedef ExteriorLights_<ContainerAllocator> Type;

  ExteriorLights_()
    : value(0)  {
    }
  ExteriorLights_(const ContainerAllocator& _alloc)
    : value(0)  {
  (void)_alloc;
    }



   typedef uint8_t _value_type;
  _value_type value;



  enum {
    LOW_BEAM_HEADLIGHTS = 1u,
    HIGH_BEAM_HEADLIGHTS = 2u,
    LEFT_TURN_SIGNAL = 4u,
    RIGHT_TURN_SIGNAL = 8u,
    DAYTIME_RUNNING_LIGHTS = 16u,
    REVERSE_LIGHT = 32u,
    FOG_LIGHT = 64u,
    PARKING_LIGHTS = 128u,
  };


  typedef boost::shared_ptr< ::etsi_msgs::ExteriorLights_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::etsi_msgs::ExteriorLights_<ContainerAllocator> const> ConstPtr;

}; // struct ExteriorLights_

typedef ::etsi_msgs::ExteriorLights_<std::allocator<void> > ExteriorLights;

typedef boost::shared_ptr< ::etsi_msgs::ExteriorLights > ExteriorLightsPtr;
typedef boost::shared_ptr< ::etsi_msgs::ExteriorLights const> ExteriorLightsConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::etsi_msgs::ExteriorLights_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::etsi_msgs::ExteriorLights_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace etsi_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'etsi_msgs': ['/home/ppe2021/catkin_ws/src/etsi_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::etsi_msgs::ExteriorLights_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::etsi_msgs::ExteriorLights_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::etsi_msgs::ExteriorLights_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::etsi_msgs::ExteriorLights_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::etsi_msgs::ExteriorLights_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::etsi_msgs::ExteriorLights_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::etsi_msgs::ExteriorLights_<ContainerAllocator> >
{
  static const char* value()
  {
    return "345ae8f2de1fe5f50829808e9f147b8c";
  }

  static const char* value(const ::etsi_msgs::ExteriorLights_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x345ae8f2de1fe5f5ULL;
  static const uint64_t static_value2 = 0x0829808e9f147b8cULL;
};

template<class ContainerAllocator>
struct DataType< ::etsi_msgs::ExteriorLights_<ContainerAllocator> >
{
  static const char* value()
  {
    return "etsi_msgs/ExteriorLights";
  }

  static const char* value(const ::etsi_msgs::ExteriorLights_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::etsi_msgs::ExteriorLights_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 value\n\
\n\
uint8 LOW_BEAM_HEADLIGHTS = 1\n\
uint8 HIGH_BEAM_HEADLIGHTS = 2\n\
uint8 LEFT_TURN_SIGNAL = 4\n\
uint8 RIGHT_TURN_SIGNAL = 8\n\
uint8 DAYTIME_RUNNING_LIGHTS = 16\n\
uint8 REVERSE_LIGHT = 32\n\
uint8 FOG_LIGHT = 64\n\
uint8 PARKING_LIGHTS = 128\n\
";
  }

  static const char* value(const ::etsi_msgs::ExteriorLights_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::etsi_msgs::ExteriorLights_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExteriorLights_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::etsi_msgs::ExteriorLights_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::etsi_msgs::ExteriorLights_<ContainerAllocator>& v)
  {
    s << indent << "value: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ETSI_MSGS_MESSAGE_EXTERIORLIGHTS_H
