// Generated by gencpp from file etsi_msgs/Heading.msg
// DO NOT EDIT!


#ifndef ETSI_MSGS_MESSAGE_HEADING_H
#define ETSI_MSGS_MESSAGE_HEADING_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <etsi_msgs/plugin/Heading.h>

namespace etsi_msgs
{
template <class ContainerAllocator>
struct Heading_
{
  typedef Heading_<ContainerAllocator> Type;

#ifdef ETSI_MSGS_MESSAGE_HEADING_PLUGIN_CONSTRUCTOR
  ETSI_MSGS_MESSAGE_HEADING_PLUGIN_CONSTRUCTOR
#else
  Heading_()
    : value(0)
    , confidence(0)  {
    }
  Heading_(const ContainerAllocator& _alloc)
    : value(0)
    , confidence(0)  {
  (void)_alloc;
    }

#endif


   typedef uint16_t _value_type;
  _value_type value;

   typedef uint8_t _confidence_type;
  _confidence_type confidence;



  enum {
    VALUE_NORTH = 0u,
    VALUE_EAST = 900u,
    VALUE_SOUTH = 1800u,
    VALUE_WEST = 2700u,
    VALUE_UNAVAILABLE = 3601u,
    CONFIDENCE_ZERO_POINT_ONE_DEGREE = 1u,
    CONFIDENCE_ONE_DEGREE = 10u,
    CONFIDENCE_OUT_OF_RANGE = 126u,
    CONFIDENCE_UNAVAILABLE = 127u,
  };


  typedef boost::shared_ptr< ::etsi_msgs::Heading_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::etsi_msgs::Heading_<ContainerAllocator> const> ConstPtr;

#ifdef ETSI_MSGS_MESSAGE_HEADING_PLUGIN_CLASS_BODY
  ETSI_MSGS_MESSAGE_HEADING_PLUGIN_CLASS_BODY
#endif
}; // struct Heading_

typedef ::etsi_msgs::Heading_<std::allocator<void> > Heading;

typedef boost::shared_ptr< ::etsi_msgs::Heading > HeadingPtr;
typedef boost::shared_ptr< ::etsi_msgs::Heading const> HeadingConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::etsi_msgs::Heading_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::etsi_msgs::Heading_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace etsi_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'etsi_msgs': ['/home/ppe2021/catkin_ws/src/etsi_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::etsi_msgs::Heading_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::etsi_msgs::Heading_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::etsi_msgs::Heading_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::etsi_msgs::Heading_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::etsi_msgs::Heading_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::etsi_msgs::Heading_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::etsi_msgs::Heading_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c491303b4798d5acaf220800ce478c5d";
  }

  static const char* value(const ::etsi_msgs::Heading_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc491303b4798d5acULL;
  static const uint64_t static_value2 = 0xaf220800ce478c5dULL;
};

template<class ContainerAllocator>
struct DataType< ::etsi_msgs::Heading_<ContainerAllocator> >
{
  static const char* value()
  {
    return "etsi_msgs/Heading";
  }

  static const char* value(const ::etsi_msgs::Heading_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::etsi_msgs::Heading_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 value # 0.1 degree\n\
uint8 confidence\n\
\n\
uint16 VALUE_NORTH = 0\n\
uint16 VALUE_EAST = 900\n\
uint16 VALUE_SOUTH = 1800\n\
uint16 VALUE_WEST = 2700\n\
uint16 VALUE_UNAVAILABLE = 3601\n\
\n\
uint8 CONFIDENCE_ZERO_POINT_ONE_DEGREE = 1\n\
uint8 CONFIDENCE_ONE_DEGREE = 10\n\
uint8 CONFIDENCE_OUT_OF_RANGE = 126\n\
uint8 CONFIDENCE_UNAVAILABLE = 127\n\
";
  }

  static const char* value(const ::etsi_msgs::Heading_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

#ifdef ETSI_MSGS_MESSAGE_HEADING_PLUGIN_SERIALIZER
  ETSI_MSGS_MESSAGE_HEADING_PLUGIN_SERIALIZER
#else
  template<class ContainerAllocator> struct Serializer< ::etsi_msgs::Heading_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value);
      stream.next(m.confidence);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Heading_
#endif

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

#ifdef ETSI_MSGS_MESSAGE_HEADING_PLUGIN_PRINTER
  ETSI_MSGS_MESSAGE_HEADING_PLUGIN_PRINTER
#else
template<class ContainerAllocator>
struct Printer< ::etsi_msgs::Heading_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::etsi_msgs::Heading_<ContainerAllocator>& v)
  {
    s << indent << "value: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.value);
    s << indent << "confidence: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.confidence);
  }
};
#endif

} // namespace message_operations
} // namespace ros

#endif // ETSI_MSGS_MESSAGE_HEADING_H
