// Generated by gencpp from file etsi_msgs/PathDeltaTime.msg
// DO NOT EDIT!


#ifndef ETSI_MSGS_MESSAGE_PATHDELTATIME_H
#define ETSI_MSGS_MESSAGE_PATHDELTATIME_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace etsi_msgs
{
template <class ContainerAllocator>
struct PathDeltaTime_
{
  typedef PathDeltaTime_<ContainerAllocator> Type;

  PathDeltaTime_()
    : value(0)  {
    }
  PathDeltaTime_(const ContainerAllocator& _alloc)
    : value(0)  {
  (void)_alloc;
    }



   typedef uint16_t _value_type;
  _value_type value;



  enum {
    UNAVAILABLE = 0u,
    TEN_MILLISECONDS_IN_PAST = 1u,
  };


  typedef boost::shared_ptr< ::etsi_msgs::PathDeltaTime_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::etsi_msgs::PathDeltaTime_<ContainerAllocator> const> ConstPtr;

}; // struct PathDeltaTime_

typedef ::etsi_msgs::PathDeltaTime_<std::allocator<void> > PathDeltaTime;

typedef boost::shared_ptr< ::etsi_msgs::PathDeltaTime > PathDeltaTimePtr;
typedef boost::shared_ptr< ::etsi_msgs::PathDeltaTime const> PathDeltaTimeConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::etsi_msgs::PathDeltaTime_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::etsi_msgs::PathDeltaTime_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace etsi_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'etsi_msgs': ['/home/ppe2021/catkin_ws/src/etsi_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::etsi_msgs::PathDeltaTime_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::etsi_msgs::PathDeltaTime_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::etsi_msgs::PathDeltaTime_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::etsi_msgs::PathDeltaTime_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::etsi_msgs::PathDeltaTime_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::etsi_msgs::PathDeltaTime_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::etsi_msgs::PathDeltaTime_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5c0695d8e0c2e70267666b597c8d9aee";
  }

  static const char* value(const ::etsi_msgs::PathDeltaTime_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5c0695d8e0c2e702ULL;
  static const uint64_t static_value2 = 0x67666b597c8d9aeeULL;
};

template<class ContainerAllocator>
struct DataType< ::etsi_msgs::PathDeltaTime_<ContainerAllocator> >
{
  static const char* value()
  {
    return "etsi_msgs/PathDeltaTime";
  }

  static const char* value(const ::etsi_msgs::PathDeltaTime_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::etsi_msgs::PathDeltaTime_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 value # 10 ms\n\
\n\
uint16 UNAVAILABLE = 0\n\
uint16 TEN_MILLISECONDS_IN_PAST = 1\n\
";
  }

  static const char* value(const ::etsi_msgs::PathDeltaTime_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::etsi_msgs::PathDeltaTime_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PathDeltaTime_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::etsi_msgs::PathDeltaTime_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::etsi_msgs::PathDeltaTime_<ContainerAllocator>& v)
  {
    s << indent << "value: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ETSI_MSGS_MESSAGE_PATHDELTATIME_H
