// Generated by gencpp from file etsi_msgs/RelevanceTrafficDirection.msg
// DO NOT EDIT!


#ifndef ETSI_MSGS_MESSAGE_RELEVANCETRAFFICDIRECTION_H
#define ETSI_MSGS_MESSAGE_RELEVANCETRAFFICDIRECTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <etsi_msgs/plugin/RelevanceTrafficDirection.h>

namespace etsi_msgs
{
template <class ContainerAllocator>
struct RelevanceTrafficDirection_
{
  typedef RelevanceTrafficDirection_<ContainerAllocator> Type;

#ifdef ETSI_MSGS_MESSAGE_RELEVANCETRAFFICDIRECTION_PLUGIN_CONSTRUCTOR
  ETSI_MSGS_MESSAGE_RELEVANCETRAFFICDIRECTION_PLUGIN_CONSTRUCTOR
#else
  RelevanceTrafficDirection_()
    : value(0)  {
    }
  RelevanceTrafficDirection_(const ContainerAllocator& _alloc)
    : value(0)  {
  (void)_alloc;
    }

#endif


   typedef uint8_t _value_type;
  _value_type value;



  enum {
    ALL_TRAFFIC_DIRECTIONS = 0u,
    UPSTREAM_TRAFFIC = 1u,
    DOWNSTREAM_TRAFFIC = 2u,
    OPPOSITE_TRAFFIC = 3u,
    UNAVAILABLE = 255u,
  };


  typedef boost::shared_ptr< ::etsi_msgs::RelevanceTrafficDirection_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::etsi_msgs::RelevanceTrafficDirection_<ContainerAllocator> const> ConstPtr;

#ifdef ETSI_MSGS_MESSAGE_RELEVANCETRAFFICDIRECTION_PLUGIN_CLASS_BODY
  ETSI_MSGS_MESSAGE_RELEVANCETRAFFICDIRECTION_PLUGIN_CLASS_BODY
#endif
}; // struct RelevanceTrafficDirection_

typedef ::etsi_msgs::RelevanceTrafficDirection_<std::allocator<void> > RelevanceTrafficDirection;

typedef boost::shared_ptr< ::etsi_msgs::RelevanceTrafficDirection > RelevanceTrafficDirectionPtr;
typedef boost::shared_ptr< ::etsi_msgs::RelevanceTrafficDirection const> RelevanceTrafficDirectionConstPtr;

// constants requiring out of line definition

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::etsi_msgs::RelevanceTrafficDirection_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::etsi_msgs::RelevanceTrafficDirection_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace etsi_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'etsi_msgs': ['/home/ppe2021/catkin_ws/src/etsi_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::etsi_msgs::RelevanceTrafficDirection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::etsi_msgs::RelevanceTrafficDirection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::etsi_msgs::RelevanceTrafficDirection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::etsi_msgs::RelevanceTrafficDirection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::etsi_msgs::RelevanceTrafficDirection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::etsi_msgs::RelevanceTrafficDirection_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::etsi_msgs::RelevanceTrafficDirection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "77aec5a7651c0ef00896308be8f8300e";
  }

  static const char* value(const ::etsi_msgs::RelevanceTrafficDirection_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x77aec5a7651c0ef0ULL;
  static const uint64_t static_value2 = 0x0896308be8f8300eULL;
};

template<class ContainerAllocator>
struct DataType< ::etsi_msgs::RelevanceTrafficDirection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "etsi_msgs/RelevanceTrafficDirection";
  }

  static const char* value(const ::etsi_msgs::RelevanceTrafficDirection_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::etsi_msgs::RelevanceTrafficDirection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 value\n\
\n\
uint8 ALL_TRAFFIC_DIRECTIONS = 0\n\
uint8 UPSTREAM_TRAFFIC = 1\n\
uint8 DOWNSTREAM_TRAFFIC = 2\n\
uint8 OPPOSITE_TRAFFIC = 3\n\
uint8 UNAVAILABLE = 255 # extension to encode optional traffic directions\n\
";
  }

  static const char* value(const ::etsi_msgs::RelevanceTrafficDirection_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

#ifdef ETSI_MSGS_MESSAGE_RELEVANCETRAFFICDIRECTION_PLUGIN_SERIALIZER
  ETSI_MSGS_MESSAGE_RELEVANCETRAFFICDIRECTION_PLUGIN_SERIALIZER
#else
  template<class ContainerAllocator> struct Serializer< ::etsi_msgs::RelevanceTrafficDirection_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RelevanceTrafficDirection_
#endif

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

#ifdef ETSI_MSGS_MESSAGE_RELEVANCETRAFFICDIRECTION_PLUGIN_PRINTER
  ETSI_MSGS_MESSAGE_RELEVANCETRAFFICDIRECTION_PLUGIN_PRINTER
#else
template<class ContainerAllocator>
struct Printer< ::etsi_msgs::RelevanceTrafficDirection_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::etsi_msgs::RelevanceTrafficDirection_<ContainerAllocator>& v)
  {
    s << indent << "value: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.value);
  }
};
#endif

} // namespace message_operations
} // namespace ros

#endif // ETSI_MSGS_MESSAGE_RELEVANCETRAFFICDIRECTION_H
