// Generated by gencpp from file etsi_msgs/VehicleRole.msg
// DO NOT EDIT!


#ifndef ETSI_MSGS_MESSAGE_VEHICLEROLE_H
#define ETSI_MSGS_MESSAGE_VEHICLEROLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace etsi_msgs
{
template <class ContainerAllocator>
struct VehicleRole_
{
  typedef VehicleRole_<ContainerAllocator> Type;

  VehicleRole_()
    : value(0)  {
    }
  VehicleRole_(const ContainerAllocator& _alloc)
    : value(0)  {
  (void)_alloc;
    }



   typedef uint8_t _value_type;
  _value_type value;



  enum {
    DEFAULT = 0u,
    PUBLIC_TRANSPORT = 1u,
    SPECIAL_TRANSPORT = 2u,
    DANGEROUS_GOODS = 3u,
    ROAD_WORK = 4u,
    RESCUE = 5u,
    EMERGENCY = 6u,
    SAFETY_CAR = 7u,
    AGRICULTURE = 8u,
    COMMERCIAL = 9u,
    MILITARY = 10u,
    ROAD_OPERATOR = 11u,
    TAXI = 12u,
  };


  typedef boost::shared_ptr< ::etsi_msgs::VehicleRole_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::etsi_msgs::VehicleRole_<ContainerAllocator> const> ConstPtr;

}; // struct VehicleRole_

typedef ::etsi_msgs::VehicleRole_<std::allocator<void> > VehicleRole;

typedef boost::shared_ptr< ::etsi_msgs::VehicleRole > VehicleRolePtr;
typedef boost::shared_ptr< ::etsi_msgs::VehicleRole const> VehicleRoleConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::etsi_msgs::VehicleRole_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::etsi_msgs::VehicleRole_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace etsi_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'etsi_msgs': ['/home/ppe2021/catkin_ws/src/etsi_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::etsi_msgs::VehicleRole_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::etsi_msgs::VehicleRole_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::etsi_msgs::VehicleRole_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::etsi_msgs::VehicleRole_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::etsi_msgs::VehicleRole_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::etsi_msgs::VehicleRole_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::etsi_msgs::VehicleRole_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d6cea9b95e10cef110efe27272e9c052";
  }

  static const char* value(const ::etsi_msgs::VehicleRole_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd6cea9b95e10cef1ULL;
  static const uint64_t static_value2 = 0x10efe27272e9c052ULL;
};

template<class ContainerAllocator>
struct DataType< ::etsi_msgs::VehicleRole_<ContainerAllocator> >
{
  static const char* value()
  {
    return "etsi_msgs/VehicleRole";
  }

  static const char* value(const ::etsi_msgs::VehicleRole_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::etsi_msgs::VehicleRole_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 value\n\
\n\
uint8 DEFAULT = 0\n\
uint8 PUBLIC_TRANSPORT = 1\n\
uint8 SPECIAL_TRANSPORT = 2\n\
uint8 DANGEROUS_GOODS = 3\n\
uint8 ROAD_WORK = 4\n\
uint8 RESCUE = 5\n\
uint8 EMERGENCY = 6\n\
uint8 SAFETY_CAR = 7\n\
uint8 AGRICULTURE = 8\n\
uint8 COMMERCIAL = 9\n\
uint8 MILITARY = 10\n\
uint8 ROAD_OPERATOR = 11\n\
uint8 TAXI = 12\n\
";
  }

  static const char* value(const ::etsi_msgs::VehicleRole_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::etsi_msgs::VehicleRole_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VehicleRole_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::etsi_msgs::VehicleRole_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::etsi_msgs::VehicleRole_<ContainerAllocator>& v)
  {
    s << indent << "value: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ETSI_MSGS_MESSAGE_VEHICLEROLE_H
