(cl:in-package etsi_msgs-msg)
(cl:export '(SEMI_MAJOR_CONFIDENCE-VAL
          SEMI_MAJOR_CONFIDENCE
          SEMI_MINOR_CONFIDENCE-VAL
          SEMI_MINOR_CONFIDENCE
          SEMI_MAJOR_ORIENTATION-VAL
          SEMI_MAJOR_ORIENTATION
))