(cl:in-package etsi_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          ITS_HEADER-VAL
          ITS_HEADER
          GENERATION_DELTA_TIME-VAL
          GENERATION_DELTA_TIME
          STATION_TYPE-VAL
          STATION_TYPE
          REFERENCE_POSITION-VAL
          REFERENCE_POSITION
          HIGH_FREQUENCY_CONTAINER-VAL
          HIGH_FREQUENCY_CONTAINER
          HAS_LOW_FREQUENCY_CONTAINER-VAL
          HAS_LOW_FREQUENCY_CONTAINER
          LOW_FREQUENCY_CONTAINER-VAL
          LOW_FREQUENCY_CONTAINER
))