(cl:in-package etsi_msgs-msg)
(cl:export '(ACTION_ID-VAL
          ACTION_ID
          DETECTION_TIME-VAL
          DETECTION_TIME
          REFERENCE_TIME-VAL
          REFERENCE_TIME
          TERMINATION-VAL
          TERMINATION
          EVENT_POSITION-VAL
          EVENT_POSITION
          RELEVANCE_DISTANCE-VAL
          RELEVANCE_DISTANCE
          RELEVANCE_TRAFFIC_DIRECTION-VAL
          RELEVANCE_TRAFFIC_DIRECTION
          VALIDITY_DURATION-VAL
          VALIDITY_DURATION
          TRANSMISSION_INTERVAL-VAL
          TRANSMISSION_INTERVAL
          STATION_TYPE-VAL
          STATION_TYPE
))