(cl:in-package etsi_msgs-msg)
(cl:export '(HEADING-VAL
          HEADING
          SPEED-VAL
          SPEED
          DRIVE_DIRECTION-VAL
          DRIVE_DIRECTION
          VEHICLE_LENGTH-VAL
          VEHICLE_LENGTH
          VEHICLE_WIDTH-VAL
          VEHICLE_WIDTH
          LONGITUDINAL_ACCELERATION-VAL
          LONGITUDINAL_ACCELERATION
          CURVATURE-VAL
          CURVATURE
          CURVATURE_CALCULATION_MODE-VAL
          CURVATURE_CALCULATION_MODE
          YAW_RATE-VAL
          YAW_RATE
          HAS_ACCELERATION_CONTROL-VAL
          HAS_ACCELERATION_CONTROL
          ACCELERATION_CONTROL-VAL
          ACCELERATION_CONTROL
))