# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ece_msgs/Init.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import ece_msgs.msg

class Init(genpy.Message):
  _md5sum = "98e72c61b91b7db811fccea348b6d240"
  _type = "ece_msgs/Init"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# Destination : 8 octets
ReferencePosition destination

# Actual position : 8 octets
ReferencePosition actual_position



================================================================================
MSG: ece_msgs/ReferencePosition
int64 latitude # 0.1 micro degree
int64 longitude # 0.1 micro degree
int32 altitude

int64 LATITUDE_UNAVAILABLE = 900000001
int64 LONGITUDE_UNAVAILABLE = 1800000001
int32 ALTITUDE_UNAVAILABLE = 800001
"""
  __slots__ = ['destination','actual_position']
  _slot_types = ['ece_msgs/ReferencePosition','ece_msgs/ReferencePosition']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       destination,actual_position

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Init, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.destination is None:
        self.destination = ece_msgs.msg.ReferencePosition()
      if self.actual_position is None:
        self.actual_position = ece_msgs.msg.ReferencePosition()
    else:
      self.destination = ece_msgs.msg.ReferencePosition()
      self.actual_position = ece_msgs.msg.ReferencePosition()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2qi2qi().pack(_x.destination.latitude, _x.destination.longitude, _x.destination.altitude, _x.actual_position.latitude, _x.actual_position.longitude, _x.actual_position.altitude))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.destination is None:
        self.destination = ece_msgs.msg.ReferencePosition()
      if self.actual_position is None:
        self.actual_position = ece_msgs.msg.ReferencePosition()
      end = 0
      _x = self
      start = end
      end += 40
      (_x.destination.latitude, _x.destination.longitude, _x.destination.altitude, _x.actual_position.latitude, _x.actual_position.longitude, _x.actual_position.altitude,) = _get_struct_2qi2qi().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2qi2qi().pack(_x.destination.latitude, _x.destination.longitude, _x.destination.altitude, _x.actual_position.latitude, _x.actual_position.longitude, _x.actual_position.altitude))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.destination is None:
        self.destination = ece_msgs.msg.ReferencePosition()
      if self.actual_position is None:
        self.actual_position = ece_msgs.msg.ReferencePosition()
      end = 0
      _x = self
      start = end
      end += 40
      (_x.destination.latitude, _x.destination.longitude, _x.destination.altitude, _x.actual_position.latitude, _x.actual_position.longitude, _x.actual_position.altitude,) = _get_struct_2qi2qi().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2qi2qi = None
def _get_struct_2qi2qi():
    global _struct_2qi2qi
    if _struct_2qi2qi is None:
        _struct_2qi2qi = struct.Struct("<2qi2qi")
    return _struct_2qi2qi
