(cl:defpackage simu_msgs-msg
  (:use )
  (:export
   "<ALTITUDE>"
   "ALTITUDE"
   "<ITSPDUHEADER>"
   "ITSPDUHEADER"
   "<POSITIONCONFIDENCEELLIPSE>"
   "POSITIONCONFIDENCEELLIPSE"
   "<REFERENCEPOSITION>"
   "REFERENCEPOSITION"
   "<SPEED>"
   "SPEED"
   "<VEHICLELENGTH>"
   "VEHICLELENGTH"
   "<SIMU_CAM>"
   "SIMU_CAM"
   "<SIMU_ECE>"
   "SIMU_ECE"
  ))

