# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from etsi_msgs/PositionConfidenceEllipse.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class PositionConfidenceEllipse(genpy.Message):
  _md5sum = "c20c3376bfa1f7fa4fce4f692844e203"
  _type = "etsi_msgs/PositionConfidenceEllipse"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint16 semi_major_confidence # cm
uint16 semi_minor_confidence # cm
uint16 semi_major_orientation # 0.1 degree

uint16 SEMI_AXIS_LENGTH_OUT_OF_RANGE = 4094
uint16 SEMI_AXIS_LENGTH_UNAVAILABLE = 4095
"""
  # Pseudo-constants
  SEMI_AXIS_LENGTH_OUT_OF_RANGE = 4094
  SEMI_AXIS_LENGTH_UNAVAILABLE = 4095

  __slots__ = ['semi_major_confidence','semi_minor_confidence','semi_major_orientation']
  _slot_types = ['uint16','uint16','uint16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       semi_major_confidence,semi_minor_confidence,semi_major_orientation

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PositionConfidenceEllipse, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.semi_major_confidence is None:
        self.semi_major_confidence = 0
      if self.semi_minor_confidence is None:
        self.semi_minor_confidence = 0
      if self.semi_major_orientation is None:
        self.semi_major_orientation = 0
    else:
      self.semi_major_confidence = 0
      self.semi_minor_confidence = 0
      self.semi_major_orientation = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3H().pack(_x.semi_major_confidence, _x.semi_minor_confidence, _x.semi_major_orientation))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 6
      (_x.semi_major_confidence, _x.semi_minor_confidence, _x.semi_major_orientation,) = _get_struct_3H().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3H().pack(_x.semi_major_confidence, _x.semi_minor_confidence, _x.semi_major_orientation))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 6
      (_x.semi_major_confidence, _x.semi_minor_confidence, _x.semi_major_orientation,) = _get_struct_3H().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3H = None
def _get_struct_3H():
    global _struct_3H
    if _struct_3H is None:
        _struct_3H = struct.Struct("<3H")
    return _struct_3H
