# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from etsi_msgs/ReferencePosition.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import etsi_msgs.msg

class ReferencePosition(genpy.Message):
  _md5sum = "a3cec6171339bd488bc9f812c2670f12"
  _type = "etsi_msgs/ReferencePosition"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int64 latitude # 0.1 micro degree
int64 longitude # 0.1 micro degree
PositionConfidenceEllipse position_confidence
Altitude altitude

int64 LATITUDE_UNAVAILABLE = 900000001
int64 LONGITUDE_UNAVAILABLE = 1800000001

================================================================================
MSG: etsi_msgs/PositionConfidenceEllipse
uint16 semi_major_confidence # cm
uint16 semi_minor_confidence # cm
uint16 semi_major_orientation # 0.1 degree

uint16 SEMI_AXIS_LENGTH_OUT_OF_RANGE = 4094
uint16 SEMI_AXIS_LENGTH_UNAVAILABLE = 4095

================================================================================
MSG: etsi_msgs/Altitude
int32 value # 0.01 meter
uint8 confidence

int32 VALUE_REFERENCE_ELLIPSOID_SURFACE = 0
int32 VALUE_ONE_CENTIMETER = 1
int32 VALUE_UNAVAILABLE = 800001

uint8 CONFIDENCE_1CM = 0
uint8 CONFIDENCE_2CM = 1
uint8 CONFIDENCE_5CM = 2
uint8 CONFIDENCE_10CM = 3
uint8 CONFIDENCE_20CM = 4
uint8 CONFIDENCE_50CM = 5
uint8 CONFIDENCE_1M = 6
uint8 CONFIDENCE_2M = 7
uint8 CONFIDENCE_5M = 8
uint8 CONFIDENCE_10M = 9
uint8 CONFIDENCE_20M = 10
uint8 CONFIDENCE_50M = 11
uint8 CONFIDENCE_100M = 12
uint8 CONFIDENCE_200M = 13
uint8 CONFIDENCE_OUT_OF_RANGE = 14
uint8 CONFIDENCE_UNAVAILABLE = 15
"""
  # Pseudo-constants
  LATITUDE_UNAVAILABLE = 900000001
  LONGITUDE_UNAVAILABLE = 1800000001

  __slots__ = ['latitude','longitude','position_confidence','altitude']
  _slot_types = ['int64','int64','etsi_msgs/PositionConfidenceEllipse','etsi_msgs/Altitude']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       latitude,longitude,position_confidence,altitude

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ReferencePosition, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.latitude is None:
        self.latitude = 0
      if self.longitude is None:
        self.longitude = 0
      if self.position_confidence is None:
        self.position_confidence = etsi_msgs.msg.PositionConfidenceEllipse()
      if self.altitude is None:
        self.altitude = etsi_msgs.msg.Altitude()
    else:
      self.latitude = 0
      self.longitude = 0
      self.position_confidence = etsi_msgs.msg.PositionConfidenceEllipse()
      self.altitude = etsi_msgs.msg.Altitude()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2q3HiB().pack(_x.latitude, _x.longitude, _x.position_confidence.semi_major_confidence, _x.position_confidence.semi_minor_confidence, _x.position_confidence.semi_major_orientation, _x.altitude.value, _x.altitude.confidence))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.position_confidence is None:
        self.position_confidence = etsi_msgs.msg.PositionConfidenceEllipse()
      if self.altitude is None:
        self.altitude = etsi_msgs.msg.Altitude()
      end = 0
      _x = self
      start = end
      end += 27
      (_x.latitude, _x.longitude, _x.position_confidence.semi_major_confidence, _x.position_confidence.semi_minor_confidence, _x.position_confidence.semi_major_orientation, _x.altitude.value, _x.altitude.confidence,) = _get_struct_2q3HiB().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2q3HiB().pack(_x.latitude, _x.longitude, _x.position_confidence.semi_major_confidence, _x.position_confidence.semi_minor_confidence, _x.position_confidence.semi_major_orientation, _x.altitude.value, _x.altitude.confidence))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.position_confidence is None:
        self.position_confidence = etsi_msgs.msg.PositionConfidenceEllipse()
      if self.altitude is None:
        self.altitude = etsi_msgs.msg.Altitude()
      end = 0
      _x = self
      start = end
      end += 27
      (_x.latitude, _x.longitude, _x.position_confidence.semi_major_confidence, _x.position_confidence.semi_minor_confidence, _x.position_confidence.semi_major_orientation, _x.altitude.value, _x.altitude.confidence,) = _get_struct_2q3HiB().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2q3HiB = None
def _get_struct_2q3HiB():
    global _struct_2q3HiB
    if _struct_2q3HiB is None:
        _struct_2q3HiB = struct.Struct("<2q3HiB")
    return _struct_2q3HiB
